Initial development
Febius/surveyjs-php-sdk pull request #1
Opened 2019-10-08 11:17 UTC by Febius

Add base models and parsers + tests

2019-10-08 11:52 UTC, astronati commented on .gitignore
> +vendor/
Let's avoid to manually add new line at the end of file.
Add `phpstan/phpstan` as dependency and run it as level 4

2019-10-08 12:15 UTC, astronati requested changes

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyChoiceModel.php
> +class SurveyChoiceModel
I would suggest you to create an `Element` folder.

Let's put in that:
- AbstractElement
- DefaultElement
- ChoiceModelElement (without naming it "Survey")
- ...

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyChoiceModel.php
> +
Take into account PHP will avoid us to use so many blank lines

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyChoiceModel.php
> +     * @return string
I would avoid to use docblock where not needed.

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyChoiceModel.php
> +    public function setValue($value): self
Do we have a type? IMHO It should be always a string.
Furthermore you defined the getter has to return a string

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyChoiceModel.php
> +    public function setText($text): self
missing type

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +    private $type;
Let's move shared properties in the abstract

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +    private $choices;
Not use a null but an empty array.

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +    private $enableIf;
Are you sure it's a string?

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +    public function setType($type): self
missing param

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +    public function setIsRequired($isRequired): self
setRequired

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +    private $isRequired;
rename it into required. Let's use adjective for boolean values and let's use "is" instead of "get" for the getter

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +    public function isValidResult(SurveyResultModel $result): bool
Let's define it as abstract in the abstract class

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +            if($this->getType() === 'comment'){
Let's define a comment element where returning always true

2019-10-08 12:15 UTC, astronati commented on src/Model/SurveyElementModel.php
> +            foreach($this->getChoices() as $choice){
Let's move it in the ChoiceElement

2019-10-11 08:34 UTC, astronati requested changes

2019-10-11 08:34 UTC, astronati commented on composer.json
> +}
Didn't php stan fixed the missing new lines?

2019-10-11 08:34 UTC, astronati commented on src/Exception/ElementPropertyNotFoundException.php
> +
PHPStan should avoid to use double blank lines when not needed as well

2019-10-11 08:34 UTC, astronati commented on src/Factory/ElementModelFactory.php
> +    public const COMMENT_TYPE = 'comment';
Let's use integer or string in UPPER_CASE as values

2019-10-11 08:34 UTC, astronati commented on src/Factory/ElementModelFactory.php
> +        self::COMMENT_TYPE      => CommentElement::class,
Were spaces added by PHPStan or did you do that manually?

2019-10-11 08:34 UTC, astronati commented on src/Factory/ElementModelFactory.php
> +    public static function getModel(string $type): AbstractSurveyElementModel
I would rename it into `create`.

Furthermore I would expect to return always a filled model and not an empty one.

2019-10-11 09:52 UTC, astronati requested changes

2019-10-11 09:52 UTC, astronati commented on src/Parser/SurveyChoiceParser.php
> +
Let's remove unnecessary blank lines

2019-10-11 09:52 UTC, astronati commented on src/Model/SurveyTemplateModel.php
> +    private $showPageTitles;
Remind me to discuss about this face to face

2019-10-11 09:52 UTC, astronati commented on src/Model/SurveyTemplateModel.php
> +
I would expect to remove even this blank line with phpstan

2019-10-11 09:52 UTC, astronati commented on src/Parser/SurveyElementParser.php
> +class SurveyElementParser
This parser does too many things

I would expect different parsers. Each parser is specific for the given element

2019-10-11 09:52 UTC, astronati commented on src/Parser/SurveyElementParser.php
> +class SurveyElementParser
The factory above has to use the most appropriate parser

2019-10-11 09:52 UTC, astronati commented on src/Factory/ElementModelFactory.php
> +    public const TYPE_TO_CLASS_MAP = [
This list introduces complexity and it does not give me a better readability.

I would expect a `switch` in the `create` method, that using the given type, uses the most appropriate parser and return a filled model.

2019-10-11 09:52 UTC, astronati commented on src/Parser/SurveyElementParser.php
> +    public static function parseToModel(array $elements): array
it shouldn't return a model and not a list. It does too many things IMHO

2019-10-11 14:39 UTC, astronati commented on composer.json
> +}
Sorry it should be `squizlabs/php_codesniffer`

2019-10-11 14:49 UTC, astronati commented on composer.json
> +  "require-dev": {
You missed:
- name
- description
- author
- version

2019-10-11 14:55 UTC, astronati commented
Next steps:
- git tag
- packagist
- github pages

2019-10-12 11:42 UTC, Febius commented on src/Factory/ElementModelFactory.php
> +    public const COMMENT_TYPE = 'comment';
what do you mean?

2019-10-14 07:58 UTC, merged